// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV0nrMoYbRZlJePV8bgR9ooB-n_yflFAk',
    appId: '1:619248145966:web:da2a492c6a703540a9f1bf',
    messagingSenderId: '619248145966',
    projectId: 'tunesync-f277f',
    authDomain: 'tunesync-f277f.firebaseapp.com',
    storageBucket: 'tunesync-f277f.firebasestorage.app',
    measurementId: 'G-BRPG7QETVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg0vT4hkguELiQ553YoUagAk4tgXvzZQ8',
    appId: '1:619248145966:android:ecf20e388f7f744ba9f1bf',
    messagingSenderId: '619248145966',
    projectId: 'tunesync-f277f',
    storageBucket: 'tunesync-f277f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB-M9jHaSS36cEGrLpKxtSsrfigwv2rRg',
    appId: '1:619248145966:ios:210c3df1f543ed5aa9f1bf',
    messagingSenderId: '619248145966',
    projectId: 'tunesync-f277f',
    storageBucket: 'tunesync-f277f.firebasestorage.app',
    iosBundleId: 'com.example.tunesync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB-M9jHaSS36cEGrLpKxtSsrfigwv2rRg',
    appId: '1:619248145966:ios:210c3df1f543ed5aa9f1bf',
    messagingSenderId: '619248145966',
    projectId: 'tunesync-f277f',
    storageBucket: 'tunesync-f277f.firebasestorage.app',
    iosBundleId: 'com.example.tunesync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV0nrMoYbRZlJePV8bgR9ooB-n_yflFAk',
    appId: '1:619248145966:web:1ad54d2433d3383aa9f1bf',
    messagingSenderId: '619248145966',
    projectId: 'tunesync-f277f',
    authDomain: 'tunesync-f277f.firebaseapp.com',
    storageBucket: 'tunesync-f277f.firebasestorage.app',
    measurementId: 'G-85C1E1ZH4C',
  );
}
